### ISSUE TITLE
Effects for actions within batch action are not triggered

### ISSUE THREAD

**Issue by biosphere-labs** [xipheCom/ngrx-batch-action-reducer#2]
This is a great library ensuring that a sequence of actions are reduced in the desired order. 

But also to compose actions from existing atomic actions and keep reducers simple.

The problem I had when integrating it today is now the effects for actions contained in a new batch action are not triggered and the only solution seems to be to create a new effect for batch action types and then have to write special logic to extract the actions they contain so that I can augment those payloads as is already handled in effects for those actions not contained in a batch action.

Which essentially violates DRY.

So how might I go about ensuring existing effects are applied to actions contained in the batch action?

**Comment by progral** [comment]
Could you provide a minimal repo as a playground and reproduction steps? I have not very much time these days. but would have a look.

**Comment by Pokerkoffer** [comment]
i can confirm this, using the ngrx example app. I created an effect that creates a batchedaction which are only processed in an effect as well. Any ideas why this happens?

**Comment by progral** [comment]
@fluidnotions , @Pokerkoffer Just to be clear: You have a batch action and there are several actions in it, right? And if you make a batch action like so:

```typescript
//somewhere in your effects
return new MyBatchAction(new FooAction(), new BarAction({somePayload: 5}));
```
... you assume that FooAction should be recognized by your effects, don't you?

But this can not happen by design. All Actions within an Batchactions are not dispatched,only the state is recalculated, so they won't appear in redux dev tools and they can not recognized by effects, because they are never dispatched.

If you want to use batch actions which will be recognized by  your effects with DRY you do not need ngrx-batch-action-reducer, just write a function which will fire your actions  - but you will have all actions in your redux dev tools

```typescript
fireMyActions(fooAction: FooAction, barAction: BarAction) {
    [fooAction, barAction].forEach(item => {this.store.dispatch(item)});
}
```
Another solution:  You write an effect which is listening to myActions AND FooAction. Don't have an example in my hand, but it's just rxjs...merging streams, ...etc., ..etc.

**Comment by progral** [comment]
Closed because this is exactly what ngrx-batch-action-reducer should do.
